# Site settings
title: "davidnewton.ca"
email: "david@davidnewton.ca"
description: "David Newton, web developer."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nwtn.github.io" # the base hostname & protocol for your site
twitter_username: "newtron"
github_username:  "nwtn"
lang: "en-CA"

# Build settings
permalink: title
encoding: "utf-8"
